### ISSUE TITLE
rComments popups sometimes hide popups for other extensions/addons

### ISSUE THREAD

**Issue by azizLIGHT** [iampueroo/rComments#10]
Some browser extensions generate popups on hover of their own and can become partially hidden and obscured by rcomments comment popups. 

- Reddit Enhancement Suite examples (subreddit descriptions, user info, etc)
![Subreddit info popup obscured](https://user-images.githubusercontent.com/8013867/84573641-c8334600-ad6f-11ea-8ab1-9e92cf71529c.gif)
![User info popup obscured](https://user-images.githubusercontent.com/8013867/84573044-22caa300-ad6c-11ea-8c71-43aa84979e5d.png)

- [YouTube Peek Preview](https://greasyfork.org/en/scripts/370755-youtube-peek-preview), a userscript for Youtube links that shows video title/thumbnails:
![Video info obscured](https://user-images.githubusercontent.com/8013867/84574487-b56f4000-ad74-11ea-98af-f526062810d9.gif)

- An example where this does not occur (preferred), even after hovering off and on. The other extension overlaps rcomments popups, instead: [YouTube Link Title](https://web.archive.org/web/20190614231337/https://greasyfork.org/en/scripts/413-youtube-link-title):
![Peek 2020-06-13 13-15](https://user-images.githubusercontent.com/8013867/84574972-06346800-ad78-11ea-9b54-17af8a192b07.gif)

**Comment by iampueroo** [comment]
Fixed with [this commit](https://github.com/iampueroo/rComments/commit/74e81e73aa980fff05aa2026f032b7ff7c104735). Will resolve once the extension is updated.

**Comment by azizLIGHT** [comment]
Not sure if version 1.2.2 from Chrome's webstore (Jun 24, 2020) has the fix you committed because I still see popups being hidden by rcomments. [Here's an example on 1.2.2](https://www.reddit.com/r/trendingsubreddits/search?q=subreddit+recommendation&include_over_18=on&sort=relevance&t=all). The comment popups have links to /r/subreddits in a search like that, hovering over the /r/subreddit link makes a RES popup, which, if the rcomment popup is wide enough, will still cover the RES popup in 1.2.2

**Comment by azizLIGHT** [comment]
I got the 1.2.3 update and it solves the issue. Thank you

**Comment by azizLIGHT** [comment]
@iampueroo This update made it to Chrome store but not Firefox addons. Could you please update the Firefox version?
